### ISSUE TITLE
Add default AMD GPU targets

### ISSUE THREAD

**Issue by jglaser** [mphoward/neighbor#16]
By default, `hipcc` does not have a GPU machine target, it compiles for whatever GPU it finds in the node it's compiling on (which could be a poor display only GPU). We should add a few default targets to the `hipcc` command line... otherwise the user has to set the `HCC_AMDGPU_TARGET` environment variable, whose name is somewhat misleading if using hip-clang, which is the default with ROCM >= 3.5.0

[Here](https://github.com/glotzerlab/hoomd-blue/pull/659/commits/62da7f69882d1a6b1a24793037495ffb5b3030c0) is a template from a PR I am working on, which includes a configurable list of some standard targets.

**Comment by mphoward** [comment]
This is a good idea since I already support the CUDA arch flags. I'll add something based off your PR to set these AMD arch flags.

**Comment by mphoward** [comment]
Resolved by #19, #20, and #21
